server:
  port: 1113
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/TWashNotificationsDB
      
      auto-index-creation: true
      
  application:
    name: T-WashNotificationService
    
  jackson:
      serialization:
       write-dates-as-timestamps: false
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost    