server:
  port: 1111
  
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/TWashUsersDB
      
      auto-index-creation: true
      
  application:
    name: T-WashUserService
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost  

    